const $=id=>document.getElementById(id);let songs=[],filtered=[],shown=0,mode='all';let startsWith='all';let startsField='title';const batch=80;let favorites=new Set();try{favorites=new Set(JSON.parse(localStorage.getItem('songhub-favorites')||'[]'))}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(reset=true){const q=$('q').value.trim().toLocaleLowerCase();filtered=songs.filter(s=>(mode!=='favorites'||favorites.has(s.number))&&(!q||`${s.number} ${s.title} ${s.artist}`.toLocaleLowerCase().includes(q))&&(startsWith==='all'||String(s[startsField]||'').trim().toLocaleUpperCase().startsWith(startsWith)));const [sortField,sortDirection]=$('sort').value.split('-');const sign=sortDirection==='desc'?-1:1;filtered.sort((a,b)=>sign*(sortField==='number'?(Number(a.number)-Number(b.number)):String(a[sortField]||'').localeCompare(String(b[sortField]||''),undefined,{sensitivity:'base',numeric:true}))||a.title.localeCompare(b.title));if(reset){shown=0;$('list').replaceChildren()}const part=filtered.slice(shown,shown+batch);const frag=document.createDocumentFragment();for(const s of part){const div=document.createElement('article');div.className='song';div.innerHTML=`<span class="note">♫</span><div class="details"><div class="title">${escapeHTML(s.title)}</div><div class="artist">${escapeHTML(s.artist||'Artist not listed')}</div></div><span class="num">${escapeHTML(s.number)}</span><button class="fav ${favorites.has(s.number)?'on':''}" aria-label="Toggle favorite for ${escapeHTML(s.title)}" data-id="${escapeHTML(s.number)}">${favorites.has(s.number)?'♥':'♡'}</button>`;frag.append(div)}$('list').append(frag);shown+=part.length;$('more').hidden=shown>=filtered.length;$('count').textContent=`${filtered.length.toLocaleString()} ${filtered.length===1?'song':'songs'}`;if(!filtered.length)$('list').innerHTML='<div class="empty">No matching songs found. Try another title, artist or number.</div>'}
function buildStartsButtons(){const el=$('starts-buttons');el.replaceChildren();const choices=startsField==='title'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''):'0123456789'.split('');for(const val of ['all',...choices]){const b=document.createElement('button');b.type='button';b.textContent=val==='all'?'All':val;b.className=startsWith===val?'active':'';b.setAttribute('aria-pressed',String(startsWith===val));b.addEventListener('click',()=>{startsWith=val;buildStartsButtons();render()});el.appendChild(b)}$('starts-hint').textContent=startsField==='title'?'Choose a letter to show only titles beginning with that letter.':'Choose a digit to show only song numbers beginning with that digit.'}
$('starts-field').addEventListener('change',e=>{startsField=e.target.value;startsWith='all';buildStartsButtons();render()});buildStartsButtons();
$('list').addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(!b)return;const id=b.dataset.id;favorites.has(id)?favorites.delete(id):favorites.add(id);try{localStorage.setItem('songhub-favorites',JSON.stringify([...favorites]))}catch{}render()});$('q').addEventListener('input',()=>render());$('clear').addEventListener('click',()=>{$('q').value='';render();$('q').focus()});$('sort').addEventListener('change',()=>render());document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));render()}));$('more').addEventListener('click',()=>render(false));$('share').addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:document.title,url:location.href})}catch{}}else if(navigator.clipboard){await navigator.clipboard.writeText(location.href);$('share').textContent='✓ Copied';setTimeout(()=>$('share').textContent='↗ Share',1800)}});
fetch('songs.json').then(r=>{if(!r.ok)throw Error('Database unavailable');return r.json()}).then(data=>{songs=data;$('status').textContent='Offline-ready after first visit';render()}).catch(e=>{$('count').textContent='Could not load song database';$('status').textContent='Run using a local web server or HTTPS';console.error(e)});if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(console.warn);

const guideToggle=$('guide-toggle');if(guideToggle){guideToggle.addEventListener('click',()=>{const panel=$('guide-steps');const opening=panel.hidden;panel.hidden=!opening;guideToggle.setAttribute('aria-expanded',String(opening));guideToggle.textContent=opening?'Hide instructions':'Show instructions';});}
